paths:
  'react'             : 'react/react-with-addons'
  'react-dom'         : 'react/react-dom'
  'react-router'      : 'react-router/index'
  'react-router-shim' : 'react-router-shim/react-router-shim'
  'jquery'            : 'jquery/dist/jquery'
  'lodash'            : 'lodash/lodash'
  'flux'              : 'flux/dist/Flux'
  'es6-promise'       : 'es6-promise/promise'
  'event-emitter'     : 'eventemitter2/lib/eventemitter2'
  'object-assign'     : 'object-assign/object-assign'
  'async'             : 'requirejs-plugins/src/async'
  'moment'            : 'moment/min/moment-with-locales.min'
  'bootstrap'         : 'bootstrap/bootstrap.min'
  'material'          : 'material-kit/material.min'
  'material-kit'      : 'material-kit/material-kit'
  'jquery'            : 'jquery/jquery.min'

shim:
  'react-router-shim':
    exports: 'React'
  'react-router':
    deps: ['react-router-shim']
    exports: 'ReactRouter'
  'material-kit':
    deps: ['jquery', 'material', 'bootstrap']
  'material':
    deps: ['jquery', 'bootstrap']
  'bootstrap':
    deps: ['jquery']
    exports: 'jquery'
  'lodash':
    exports: '_'
  'object-assign':
    exports: 'ObjectAssign'
